/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Faucet__factory } from "./Faucet__factory";
export { KuwaCoin__factory } from "./KuwaCoin__factory";
export { Lock__factory } from "./Lock__factory";
