/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { KuwaCoin__factory } from "./KuwaCoin__factory";
export { MasterKuwa__factory } from "./MasterKuwa__factory";
